#include "cpptest.h"

#include "D:\CRRC\ATP-UT1-2607-copy\ATP\ATP\src\AppLogic\PeriodHandle\EbTrackCutManage\EbAndCutOffTrackOut.c"
#include "D:\CRRC\ATP-UT1-2607-copy\ATP\ATP\test\UT1\tests\autogenerated\source\applogic\periodhandle\ebtrackcutmanage\TestSuite_EbAndCutOffTrackOut_c.c"

