#line 1 "D:\\CRRC\\ATP-UT1-2607-copy\\ATP\\ATP\\test\\UT1\\stubs\\autogenerated\\auto_344e85af.c"

#define CPPTEST_INSTRUMENTATION

#include "cpptest_i.h"
#include "D:\CRRC\ATP-UT1-2607-copy\ATP\ATP\test\UT1\.cpptest\ATP_UT\unit-data\current_tubf179707\cpptest_stubconfig.h"


struct __CPTR_Dummy_Type {
    char nonEmpty;
};



#include "cpptest_runtime_i.h"

#ifdef __cplusplus
extern "C" void __CPTR_Initialize(void);
extern "C" void __CPTR_Finalize(void);

struct __CPTR_Initializer_1001308918_30040_2317011479 {
    __CPTR_Initializer_1001308918_30040_2317011479()
    {
        CPPTEST_INITIALIZE_RUNTIME();
    }
    ~__CPTR_Initializer_1001308918_30040_2317011479()
    {
        CPPTEST_FINALIZE_RUNTIME();
    }
};

#if CPPTEST_USE_GLOBAL_OBJECTS_TO_INIT_RUNTIME
static struct __CPTR_Initializer_1001308918_30040_2317011479 __CPTR_initializer_1001308918_30040_2317011479;
#endif

#define CPPTEST_ENTER_MAIN_ROUTINE() __CPTR_Initializer_1001308918_30040_2317011479 __CPTR_main_initializer

#define CPPTEST_EXIT_MAIN_ROUTINE()

#else
extern void __CPTR_Initialize(void);
extern void __CPTR_Finalize(void);

#define CPPTEST_ENTER_MAIN_ROUTINE() CPPTEST_INITIALIZE_RUNTIME()

#define CPPTEST_EXIT_MAIN_ROUTINE() CPPTEST_FINALIZE_RUNTIME()

#endif


#define _cpptest_strdata_var(id, bogus) _cpptest_strdata[id]
static 
const char* _cpptest_strdata[] = {
    0,
    0
};

#if defined(CPPTEST_STUB_SetSendAtoairConditionerStaticTestReq) || CPPTEST_ENABLE_ALL_STUBS
# if defined(CPPTEST_SAFE_STUB_SetSendAtoairConditionerStaticTestReq)
#  define CppTest_Stub__Call_SetSendAtoairConditionerStaticTestReq_SetSendAtoairConditionerStaticTestReq CppTest_Safe_Stub_SetSendAtoairConditionerStaticTestReq_SetSendAtoairConditionerStaticTestReq
#  if defined(CPPTEST_UNDEFINED_SetSendAtoairConditionerStaticTestReq)
#   define CppTest_Safe_Stub_SetSendAtoairConditionerStaticTestReq_SetSendAtoairConditionerStaticTestReq SetSendAtoairConditionerStaticTestReq
#  endif
# elif defined(CPPTEST_AUTO_STUB_SetSendAtoairConditionerStaticTestReq)
#  define CppTest_Stub__Call_SetSendAtoairConditionerStaticTestReq_SetSendAtoairConditionerStaticTestReq CppTest_Auto_Stub_SetSendAtoairConditionerStaticTestReq_SetSendAtoairConditionerStaticTestReq
#  if defined(CPPTEST_UNDEFINED_SetSendAtoairConditionerStaticTestReq)
#   define CppTest_Auto_Stub_SetSendAtoairConditionerStaticTestReq_SetSendAtoairConditionerStaticTestReq SetSendAtoairConditionerStaticTestReq
#  endif
# else
#  define CppTest_Stub__Call_SetSendAtoairConditionerStaticTestReq_SetSendAtoairConditionerStaticTestReq CppTest_Stub_SetSendAtoairConditionerStaticTestReq_SetSendAtoairConditionerStaticTestReq
#  if defined(CPPTEST_UNDEFINED_SetSendAtoairConditionerStaticTestReq)
#   define CppTest_Stub_SetSendAtoairConditionerStaticTestReq_SetSendAtoairConditionerStaticTestReq SetSendAtoairConditionerStaticTestReq
#  endif
#  define CPPTEST_USER_STUB_SetSendAtoairConditionerStaticTestReq
# endif
#else
# define CppTest_Stub__Call_SetSendAtoairConditionerStaticTestReq_SetSendAtoairConditionerStaticTestReq SetSendAtoairConditionerStaticTestReq
#endif

#if defined(CPPTEST_STUB_packSendTacAlarmInfo) || CPPTEST_ENABLE_ALL_STUBS
# if defined(CPPTEST_SAFE_STUB_packSendTacAlarmInfo)
#  define CppTest_Stub__Call_packSendTacAlarmInfo_packSendTacAlarmInfo CppTest_Safe_Stub_packSendTacAlarmInfo_packSendTacAlarmInfo
#  if defined(CPPTEST_UNDEFINED_packSendTacAlarmInfo)
#   define CppTest_Safe_Stub_packSendTacAlarmInfo_packSendTacAlarmInfo packSendTacAlarmInfo
#  endif
# elif defined(CPPTEST_AUTO_STUB_packSendTacAlarmInfo)
#  define CppTest_Stub__Call_packSendTacAlarmInfo_packSendTacAlarmInfo CppTest_Auto_Stub_packSendTacAlarmInfo_packSendTacAlarmInfo
#  if defined(CPPTEST_UNDEFINED_packSendTacAlarmInfo)
#   define CppTest_Auto_Stub_packSendTacAlarmInfo_packSendTacAlarmInfo packSendTacAlarmInfo
#  endif
# else
#  define CppTest_Stub__Call_packSendTacAlarmInfo_packSendTacAlarmInfo CppTest_Stub_packSendTacAlarmInfo_packSendTacAlarmInfo
#  if defined(CPPTEST_UNDEFINED_packSendTacAlarmInfo)
#   define CppTest_Stub_packSendTacAlarmInfo_packSendTacAlarmInfo packSendTacAlarmInfo
#  endif
#  define CPPTEST_USER_STUB_packSendTacAlarmInfo
# endif
#else
# define CppTest_Stub__Call_packSendTacAlarmInfo_packSendTacAlarmInfo packSendTacAlarmInfo
#endif

#if defined(CPPTEST_STUB_SetSendAtotrainAirTightnessTestReq) || CPPTEST_ENABLE_ALL_STUBS
# if defined(CPPTEST_SAFE_STUB_SetSendAtotrainAirTightnessTestReq)
#  define CppTest_Stub__Call_SetSendAtotrainAirTightnessTestReq_SetSendAtotrainAirTightnessTestReq CppTest_Safe_Stub_SetSendAtotrainAirTightnessTestReq_SetSendAtotrainAirTightnessTestReq
#  if defined(CPPTEST_UNDEFINED_SetSendAtotrainAirTightnessTestReq)
#   define CppTest_Safe_Stub_SetSendAtotrainAirTightnessTestReq_SetSendAtotrainAirTightnessTestReq SetSendAtotrainAirTightnessTestReq
#  endif
# elif defined(CPPTEST_AUTO_STUB_SetSendAtotrainAirTightnessTestReq)
#  define CppTest_Stub__Call_SetSendAtotrainAirTightnessTestReq_SetSendAtotrainAirTightnessTestReq CppTest_Auto_Stub_SetSendAtotrainAirTightnessTestReq_SetSendAtotrainAirTightnessTestReq
#  if defined(CPPTEST_UNDEFINED_SetSendAtotrainAirTightnessTestReq)
#   define CppTest_Auto_Stub_SetSendAtotrainAirTightnessTestReq_SetSendAtotrainAirTightnessTestReq SetSendAtotrainAirTightnessTestReq
#  endif
# else
#  define CppTest_Stub__Call_SetSendAtotrainAirTightnessTestReq_SetSendAtotrainAirTightnessTestReq CppTest_Stub_SetSendAtotrainAirTightnessTestReq_SetSendAtotrainAirTightnessTestReq
#  if defined(CPPTEST_UNDEFINED_SetSendAtotrainAirTightnessTestReq)
#   define CppTest_Stub_SetSendAtotrainAirTightnessTestReq_SetSendAtotrainAirTightnessTestReq SetSendAtotrainAirTightnessTestReq
#  endif
#  define CPPTEST_USER_STUB_SetSendAtotrainAirTightnessTestReq
# endif
#else
# define CppTest_Stub__Call_SetSendAtotrainAirTightnessTestReq_SetSendAtotrainAirTightnessTestReq SetSendAtotrainAirTightnessTestReq
#endif

#if defined(CPPTEST_STUB_GetRcvAtoFamMode) || CPPTEST_ENABLE_ALL_STUBS
# if defined(CPPTEST_SAFE_STUB_GetRcvAtoFamMode)
#  define CppTest_Stub__Call_GetRcvAtoFamMode_GetRcvAtoFamMode CppTest_Safe_Stub_GetRcvAtoFamMode_GetRcvAtoFamMode
#  if defined(CPPTEST_UNDEFINED_GetRcvAtoFamMode)
#   define CppTest_Safe_Stub_GetRcvAtoFamMode_GetRcvAtoFamMode GetRcvAtoFamMode
#  endif
# elif defined(CPPTEST_AUTO_STUB_GetRcvAtoFamMode)
#  define CppTest_Stub__Call_GetRcvAtoFamMode_GetRcvAtoFamMode CppTest_Auto_Stub_GetRcvAtoFamMode_GetRcvAtoFamMode
#  if defined(CPPTEST_UNDEFINED_GetRcvAtoFamMode)
#   define CppTest_Auto_Stub_GetRcvAtoFamMode_GetRcvAtoFamMode GetRcvAtoFamMode
#  endif
# else
#  define CppTest_Stub__Call_GetRcvAtoFamMode_GetRcvAtoFamMode CppTest_Stub_GetRcvAtoFamMode_GetRcvAtoFamMode
#  if defined(CPPTEST_UNDEFINED_GetRcvAtoFamMode)
#   define CppTest_Stub_GetRcvAtoFamMode_GetRcvAtoFamMode GetRcvAtoFamMode
#  endif
#  define CPPTEST_USER_STUB_GetRcvAtoFamMode
# endif
#else
# define CppTest_Stub__Call_GetRcvAtoFamMode_GetRcvAtoFamMode GetRcvAtoFamMode
#endif

#if defined(CPPTEST_STUB_SetSendAtoemergencyVentilationTestReq) || CPPTEST_ENABLE_ALL_STUBS
# if defined(CPPTEST_SAFE_STUB_SetSendAtoemergencyVentilationTestReq)
#  define CppTest_Stub__Call_SetSendAtoemergencyVentilationTestReq_SetSendAtoemergencyVentilationTestReq CppTest_Safe_Stub_SetSendAtoemergencyVentilationTestReq_SetSendAtoemergencyVentilationTestReq
#  if defined(CPPTEST_UNDEFINED_SetSendAtoemergencyVentilationTestReq)
#   define CppTest_Safe_Stub_SetSendAtoemergencyVentilationTestReq_SetSendAtoemergencyVentilationTestReq SetSendAtoemergencyVentilationTestReq
#  endif
# elif defined(CPPTEST_AUTO_STUB_SetSendAtoemergencyVentilationTestReq)
#  define CppTest_Stub__Call_SetSendAtoemergencyVentilationTestReq_SetSendAtoemergencyVentilationTestReq CppTest_Auto_Stub_SetSendAtoemergencyVentilationTestReq_SetSendAtoemergencyVentilationTestReq
#  if defined(CPPTEST_UNDEFINED_SetSendAtoemergencyVentilationTestReq)
#   define CppTest_Auto_Stub_SetSendAtoemergencyVentilationTestReq_SetSendAtoemergencyVentilationTestReq SetSendAtoemergencyVentilationTestReq
#  endif
# else
#  define CppTest_Stub__Call_SetSendAtoemergencyVentilationTestReq_SetSendAtoemergencyVentilationTestReq CppTest_Stub_SetSendAtoemergencyVentilationTestReq_SetSendAtoemergencyVentilationTestReq
#  if defined(CPPTEST_UNDEFINED_SetSendAtoemergencyVentilationTestReq)
#   define CppTest_Stub_SetSendAtoemergencyVentilationTestReq_SetSendAtoemergencyVentilationTestReq SetSendAtoemergencyVentilationTestReq
#  endif
#  define CPPTEST_USER_STUB_SetSendAtoemergencyVentilationTestReq
# endif
#else
# define CppTest_Stub__Call_SetSendAtoemergencyVentilationTestReq_SetSendAtoemergencyVentilationTestReq SetSendAtoemergencyVentilationTestReq
#endif

#if defined(CPPTEST_STUB_SetSendAtototalWindThroughTestReq) || CPPTEST_ENABLE_ALL_STUBS
# if defined(CPPTEST_SAFE_STUB_SetSendAtototalWindThroughTestReq)
#  define CppTest_Stub__Call_SetSendAtototalWindThroughTestReq_SetSendAtototalWindThroughTestReq CppTest_Safe_Stub_SetSendAtototalWindThroughTestReq_SetSendAtototalWindThroughTestReq
#  if defined(CPPTEST_UNDEFINED_SetSendAtototalWindThroughTestReq)
#   define CppTest_Safe_Stub_SetSendAtototalWindThroughTestReq_SetSendAtototalWindThroughTestReq SetSendAtototalWindThroughTestReq
#  endif
# elif defined(CPPTEST_AUTO_STUB_SetSendAtototalWindThroughTestReq)
#  define CppTest_Stub__Call_SetSendAtototalWindThroughTestReq_SetSendAtototalWindThroughTestReq CppTest_Auto_Stub_SetSendAtototalWindThroughTestReq_SetSendAtototalWindThroughTestReq
#  if defined(CPPTEST_UNDEFINED_SetSendAtototalWindThroughTestReq)
#   define CppTest_Auto_Stub_SetSendAtototalWindThroughTestReq_SetSendAtototalWindThroughTestReq SetSendAtototalWindThroughTestReq
#  endif
# else
#  define CppTest_Stub__Call_SetSendAtototalWindThroughTestReq_SetSendAtototalWindThroughTestReq CppTest_Stub_SetSendAtototalWindThroughTestReq_SetSendAtototalWindThroughTestReq
#  if defined(CPPTEST_UNDEFINED_SetSendAtototalWindThroughTestReq)
#   define CppTest_Stub_SetSendAtototalWindThroughTestReq_SetSendAtototalWindThroughTestReq SetSendAtototalWindThroughTestReq
#  endif
#  define CPPTEST_USER_STUB_SetSendAtototalWindThroughTestReq
# endif
#else
# define CppTest_Stub__Call_SetSendAtototalWindThroughTestReq_SetSendAtototalWindThroughTestReq SetSendAtototalWindThroughTestReq
#endif

#if defined(CPPTEST_STUB_SetSendAtomechanicalBrakingTestReq) || CPPTEST_ENABLE_ALL_STUBS
# if defined(CPPTEST_SAFE_STUB_SetSendAtomechanicalBrakingTestReq)
#  define CppTest_Stub__Call_SetSendAtomechanicalBrakingTestReq_SetSendAtomechanicalBrakingTestReq CppTest_Safe_Stub_SetSendAtomechanicalBrakingTestReq_SetSendAtomechanicalBrakingTestReq
#  if defined(CPPTEST_UNDEFINED_SetSendAtomechanicalBrakingTestReq)
#   define CppTest_Safe_Stub_SetSendAtomechanicalBrakingTestReq_SetSendAtomechanicalBrakingTestReq SetSendAtomechanicalBrakingTestReq
#  endif
# elif defined(CPPTEST_AUTO_STUB_SetSendAtomechanicalBrakingTestReq)
#  define CppTest_Stub__Call_SetSendAtomechanicalBrakingTestReq_SetSendAtomechanicalBrakingTestReq CppTest_Auto_Stub_SetSendAtomechanicalBrakingTestReq_SetSendAtomechanicalBrakingTestReq
#  if defined(CPPTEST_UNDEFINED_SetSendAtomechanicalBrakingTestReq)
#   define CppTest_Auto_Stub_SetSendAtomechanicalBrakingTestReq_SetSendAtomechanicalBrakingTestReq SetSendAtomechanicalBrakingTestReq
#  endif
# else
#  define CppTest_Stub__Call_SetSendAtomechanicalBrakingTestReq_SetSendAtomechanicalBrakingTestReq CppTest_Stub_SetSendAtomechanicalBrakingTestReq_SetSendAtomechanicalBrakingTestReq
#  if defined(CPPTEST_UNDEFINED_SetSendAtomechanicalBrakingTestReq)
#   define CppTest_Stub_SetSendAtomechanicalBrakingTestReq_SetSendAtomechanicalBrakingTestReq SetSendAtomechanicalBrakingTestReq
#  endif
#  define CPPTEST_USER_STUB_SetSendAtomechanicalBrakingTestReq
# endif
#else
# define CppTest_Stub__Call_SetSendAtomechanicalBrakingTestReq_SetSendAtomechanicalBrakingTestReq SetSendAtomechanicalBrakingTestReq
#endif


#line 11 "C:\\Program Files (x86)\\Parasoft\\C++test for Visual Studio\\9.2\\engine\\runtime\\include\\cpptest_pre.h"
struct CppTest_Dummy_Type { 
char nonEmpty; 
}; 

struct CppTest_Safe_Dummy_Type { 
char nonEmpty; 
}; 

struct CppTest_Auto_Dummy_Type { 
char nonEmpty; 
}; 
#line 40
typedef struct CppTest_Dummy_Type CppTest_Dummy; 
typedef struct CppTest_Safe_Dummy_Type CppTest_Safe_Dummy; 
typedef struct CppTest_Auto_Dummy_Type CppTest_Auto_Dummy; 
#line 29 "D:\\CRRC\\VS2010\\VC\\include\\codeanalysis\\sourceannotations.h"
typedef unsigned __w64 size_t; 
#line 35
typedef unsigned short wchar_t; 
#line 56
enum SA_YesNoMaybe { 


SA_No = 268369921, 
SA_Maybe = 268369936, 
SA_Yes = 268370176
}; 

typedef enum SA_YesNoMaybe SA_YesNoMaybe; 

enum SA_AccessType { 

SA_NoAccess, 
SA_Read, 
SA_Write, 
SA_ReadWrite
}; 

typedef enum SA_AccessType SA_AccessType; 




[source_annotation_attribute ( SA_Parameter )] 
struct PreAttribute { 
#line 86
unsigned Deref; 
SA_YesNoMaybe Valid; 
SA_YesNoMaybe Null; 
SA_YesNoMaybe Tainted; 
SA_AccessType Access; 
size_t ValidElementsConst; 
size_t ValidBytesConst; 
const wchar_t *ValidElements; 
const wchar_t *ValidBytes; 
const wchar_t *ValidElementsLength; 
const wchar_t *ValidBytesLength; 
size_t WritableElementsConst; 
size_t WritableBytesConst; 
const wchar_t *WritableElements; 
const wchar_t *WritableBytes; 
const wchar_t *WritableElementsLength; 
const wchar_t *WritableBytesLength; 
size_t ElementSizeConst; 
const wchar_t *ElementSize; 
SA_YesNoMaybe NullTerminated; 
const wchar_t *Condition; 
}; 


[source_annotation_attribute ( SA_Parameter | SA_ReturnValue )] 
struct PostAttribute { 
#line 117
unsigned Deref; 
SA_YesNoMaybe Valid; 
SA_YesNoMaybe Null; 
SA_YesNoMaybe Tainted; 
SA_AccessType Access; 
size_t ValidElementsConst; 
size_t ValidBytesConst; 
const wchar_t *ValidElements; 
const wchar_t *ValidBytes; 
const wchar_t *ValidElementsLength; 
const wchar_t *ValidBytesLength; 
size_t WritableElementsConst; 
size_t WritableBytesConst; 
const wchar_t *WritableElements; 
const wchar_t *WritableBytes; 
const wchar_t *WritableElementsLength; 
const wchar_t *WritableBytesLength; 
size_t ElementSizeConst; 
const wchar_t *ElementSize; 
SA_YesNoMaybe NullTerminated; 
SA_YesNoMaybe MustCheck; 
const wchar_t *Condition; 
}; 

[source_annotation_attribute ( SA_Parameter )] 
struct FormatStringAttribute { 
#line 148
const wchar_t *Style; 
const wchar_t *UnformattedAlternative; 
}; 


[source_annotation_attribute ( SA_ReturnValue )] 
struct InvalidCheckAttribute { 
#line 160
long Value; 
}; 

[source_annotation_attribute ( SA_Method )] 
struct SuccessAttribute { 
#line 170
const wchar_t *Condition; 
}; 


[source_annotation_attribute ( SA_Parameter )] 
struct PreBoundAttribute { 




unsigned Deref; 
}; 


[source_annotation_attribute ( SA_Parameter | SA_ReturnValue )] 
struct PostBoundAttribute { 




unsigned Deref; 
}; 


[source_annotation_attribute ( SA_Parameter )] 
struct PreRangeAttribute { 




unsigned Deref; 
const char *MinVal; 
const char *MaxVal; 
}; 


[source_annotation_attribute ( SA_Parameter | SA_ReturnValue )] 
struct PostRangeAttribute { 




unsigned Deref; 
const char *MinVal; 
const char *MaxVal; 
}; 
#line 269
typedef struct PreAttribute SA_Pre; 
typedef struct PreAttribute PreAttribute; 
typedef struct PostAttribute SA_Post; 
typedef struct PostAttribute PostAttribute; 
typedef struct FormatStringAttribute SA_FormatString; 
typedef struct InvalidCheckAttribute SA_InvalidCheck; 
typedef struct SuccessAttribute SA_Success; 
typedef struct PreBoundAttribute SA_PreBound; 
typedef struct PostBoundAttribute SA_PostBound; 
typedef struct PreRangeAttribute SA_PreRange; 
typedef struct PostRangeAttribute SA_PostRange; 
#line 61 "D:\\CRRC\\VS2010\\VC\\include\\crtdefs.h"
#pragma pack ( push, 8 )
#line 29 "D:\\CRRC\\VS2010\\VC\\include\\vadefs.h"
#pragma pack ( push, 8 )
#line 48
typedef unsigned __w64 uintptr_t; 
#line 57
typedef char *va_list; 
#line 146
#pragma pack ( pop )
#line 409 "D:\\CRRC\\VS2010\\VC\\include\\crtdefs.h"
typedef size_t rsize_t; 
#line 418
typedef int __w64 intptr_t; 
#line 436
typedef int __w64 ptrdiff_t; 
#line 447
typedef unsigned short wint_t; 
typedef unsigned short wctype_t; 
#line 469
typedef int errno_t; 



typedef long __w64 __time32_t; 




typedef __int64 __time64_t; 
#line 486
typedef __time64_t time_t; 
#line 543
__declspec(dllimport) void __cdecl _invalid_parameter(const wchar_t *, const wchar_t *, const wchar_t *, unsigned, uintptr_t); 
#line 550
__declspec(dllimport) __declspec(noreturn) void __cdecl _invoke_watson(const wchar_t *, const wchar_t *, const wchar_t *, unsigned, uintptr_t); 
#line 1953
struct threadlocaleinfostruct; 
struct threadmbcinfostruct; 
typedef struct threadlocaleinfostruct *pthreadlocinfo; 
typedef struct threadmbcinfostruct *pthreadmbcinfo; 
struct __lc_time_data; 
#line 1963
typedef 
#line 1959
struct localeinfo_struct { 

pthreadlocinfo locinfo; 
pthreadmbcinfo mbcinfo; 
} _locale_tstruct, *_locale_t; 
#line 1970
typedef 
#line 1966
struct tagLC_ID { 
unsigned short wLanguage; 
unsigned short wCountry; 
unsigned short wCodePage; 
} LC_ID, *LPLC_ID; 
#line 1999
typedef 
#line 1975
struct threadlocaleinfostruct { 
int refcount; 
unsigned lc_codepage; 
unsigned lc_collate_cp; 
unsigned long lc_handle[6]; 
LC_ID lc_id[6]; 
struct { 
char *locale; 
wchar_t *wlocale; 
int *refcount; 
int *wrefcount; 
} lc_category[6]; 
int lc_clike; 
int mb_cur_max; 
int *lconv_intl_refcount; 
int *lconv_num_refcount; 
int *lconv_mon_refcount; 
struct lconv *lconv; 
int *ctype1_refcount; 
unsigned short *ctype1; 
const unsigned short *pctype; 
const unsigned char *pclmap; 
const unsigned char *pcumap; 
struct __lc_time_data *lc_time_curr; 
} threadlocinfo; 
#line 2036
#pragma pack ( pop )
#line 28 "D:\\CRRC\\VS2010\\VC\\include\\stdlib.h"
#pragma pack ( push, 8 )
#line 52
typedef int (__cdecl *_onexit_t)(void); 
#line 78
typedef 
#line 75
struct _div_t { 
int quot; 
int rem; 
} div_t; 




typedef 
#line 80
struct _ldiv_t { 
long quot; 
long rem; 
} ldiv_t; 




typedef 
#line 85
struct _lldiv_t { 
__int64 quot; 
__int64 rem; 
} lldiv_t; 
#line 102
#pragma pack ( 4 )


typedef 
#line 103
struct { 
unsigned char ld[10]; 
} _LDOUBLE; 
#pragma pack ( )
#line 124
typedef 
#line 122
struct { 
double x; 
} _CRT_DOUBLE; 



typedef 
#line 126
struct { 
float f; 
} _CRT_FLOAT; 
#line 139
typedef 
#line 134
struct { 



long double x; 
} _LONGDOUBLE; 



#pragma pack ( 4 )


typedef 
#line 144
struct { 
unsigned char ld12[12]; 
} _LDBL12; 
#pragma pack ( )
#line 163
__declspec(dllimport) extern int __mb_cur_max; 




__declspec(dllimport) int __cdecl ___mb_cur_max_func(void); 
__declspec(dllimport) int __cdecl ___mb_cur_max_l_func(_locale_t); 
#line 208
typedef void (__cdecl *_purecall_handler)(void); 


__declspec(dllimport) _purecall_handler __cdecl _set_purecall_handler(_purecall_handler _Handler); 
__declspec(dllimport) _purecall_handler __cdecl _get_purecall_handler(void); 
#line 228
typedef void (__cdecl *_invalid_parameter_handler)(const wchar_t *, const wchar_t *, const wchar_t *, unsigned, uintptr_t); 


__declspec(dllimport) _invalid_parameter_handler __cdecl _set_invalid_parameter_handler(_invalid_parameter_handler _Handler); 
__declspec(dllimport) _invalid_parameter_handler __cdecl _get_invalid_parameter_handler(void); 
#line 249
__declspec(dllimport) extern int *__cdecl _errno(void); 


errno_t __cdecl _set_errno(int _Value); 
errno_t __cdecl _get_errno(int * _Value); 


__declspec(dllimport) unsigned long *__cdecl __doserrno(void); 


errno_t __cdecl _set_doserrno(unsigned long _Value); 
errno_t __cdecl _get_doserrno(unsigned long * _Value); 


__declspec(dllimport) __declspec(deprecated("This function or variable may be unsafe. Consider using strerror instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. S" "ee online help for details.")) char **__cdecl __sys_errlist(void); 


__declspec(dllimport) __declspec(deprecated("This function or variable may be unsafe. Consider using strerror instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. S" "ee online help for details.")) int *__cdecl __sys_nerr(void); 




__declspec(dllimport) int *__cdecl __p___argc(void); 
__declspec(dllimport) char ***__cdecl __p___argv(void); 
__declspec(dllimport) wchar_t ***__cdecl __p___wargv(void); 
__declspec(dllimport) char ***__cdecl __p__environ(void); 
__declspec(dllimport) wchar_t ***__cdecl __p__wenviron(void); 
__declspec(dllimport) char **__cdecl __p__pgmptr(void); 
__declspec(dllimport) wchar_t **__cdecl __p__wpgmptr(void); 
#line 283
__declspec(dllimport) extern int __argc; 
__declspec(dllimport) extern char **__argv; 
__declspec(dllimport) extern wchar_t **__wargv; 
#line 299
__declspec(dllimport) extern char **_environ; 
__declspec(dllimport) extern wchar_t **_wenviron; 


__declspec(deprecated("This function or variable may be unsafe. Consider using _get_pgmptr instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS" ". See online help for details.")) __declspec(dllimport) extern char *_pgmptr; 
__declspec(deprecated("This function or variable may be unsafe. Consider using _get_wpgmptr instead. To disable deprecation, use _CRT_SECURE_NO_WARNING" "S. See online help for details.")) __declspec(dllimport) extern wchar_t *_wpgmptr; 
#line 321
errno_t __cdecl _get_pgmptr(char ** _Value); 
errno_t __cdecl _get_wpgmptr(wchar_t ** _Value); 



__declspec(deprecated("This function or variable may be unsafe. Consider using _get_fmode instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS." " See online help for details.")) __declspec(dllimport) extern int _fmode; 
#line 332
__declspec(dllimport) errno_t __cdecl _set_fmode(int _Mode); 
__declspec(dllimport) errno_t __cdecl _get_fmode(int * _PMode); 
#line 353
__declspec(dllimport) __declspec(noreturn) void __cdecl exit(int _Code); 
__declspec(dllimport) __declspec(noreturn) void __cdecl _exit(int _Code); 
__declspec(dllimport) void __cdecl abort(void); 


__declspec(dllimport) unsigned __cdecl _set_abort_behavior(unsigned _Flags, unsigned _Mask); 



int __cdecl abs(int _X); 
long __cdecl labs(long _X); 
__int64 __cdecl llabs(__int64 _X); 


__int64 __cdecl _abs64(__int64); 
#line 398
int __cdecl atexit(void (__cdecl *)(void)); 



__declspec(dllimport) double __cdecl atof(const char * _String); 
__declspec(dllimport) double __cdecl _atof_l(const char * _String, _locale_t _Locale); 

__declspec(dllimport) int __cdecl atoi(const char * _Str); 
__declspec(dllimport) int __cdecl _atoi_l(const char * _Str, _locale_t _Locale); 
__declspec(dllimport) long __cdecl atol(const char * _Str); 
__declspec(dllimport) long __cdecl _atol_l(const char * _Str, _locale_t _Locale); 



__declspec(dllimport) void *__cdecl bsearch_s(const void * _Key, const void * _Base, rsize_t _NumOfElements, rsize_t _SizeOfElements, int (__cdecl * _PtFuncCompare)(void *, const void *, const void *), void * _Context); 



__declspec(dllimport) void *__cdecl bsearch(const void * _Key, const void * _Base, size_t _NumOfElements, size_t _SizeOfElements, int (__cdecl * _PtFuncCompare)(const void *, const void *)); 




__declspec(dllimport) void __cdecl qsort_s(void * _Base, rsize_t _NumOfElements, rsize_t _SizeOfElements, int (__cdecl * _PtFuncCompare)(void *, const void *, const void *), void * _Context); 



__declspec(dllimport) void __cdecl qsort(void * _Base, size_t _NumOfElements, size_t _SizeOfElements, int (__cdecl * _PtFuncCompare)(const void *, const void *)); 



unsigned short __cdecl _byteswap_ushort(unsigned short _Short); 
unsigned long __cdecl _byteswap_ulong(unsigned long _Long); 
unsigned __int64 __cdecl _byteswap_uint64(unsigned __int64 _Int64); 
__declspec(dllimport) div_t __cdecl div(int _Numerator, int _Denominator); 
__declspec(dllimport) __declspec(deprecated("This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. " "See online help for details.")) char *__cdecl getenv(const char * _VarName); 

__declspec(dllimport) errno_t __cdecl getenv_s(size_t * _ReturnSize, char * _DstBuf, rsize_t _DstSize, const char * _VarName); 
#line 443
__declspec(dllimport) errno_t __cdecl _dupenv_s(char ** _PBuffer, size_t * _PBufferSizeInBytes, const char * _VarName); 
#line 449
__declspec(dllimport) errno_t __cdecl _itoa_s(int _Value, char * _DstBuf, size_t _Size, int _Radix); 

__declspec(deprecated("This function or variable may be unsafe. Consider using _itoa_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. Se" "e online help for details.")) __declspec(dllimport) char *__cdecl _itoa(int _Value, char * _Dest, int _Radix); 
__declspec(dllimport) errno_t __cdecl _i64toa_s(__int64 _Val, char * _DstBuf, size_t _Size, int _Radix); 
__declspec(dllimport) __declspec(deprecated("This function or variable may be unsafe. Consider using _i64toa_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. " "See online help for details.")) char *__cdecl _i64toa(__int64 _Val, char * _DstBuf, int _Radix); 
__declspec(dllimport) errno_t __cdecl _ui64toa_s(unsigned __int64 _Val, char * _DstBuf, size_t _Size, int _Radix); 
__declspec(dllimport) __declspec(deprecated("This function or variable may be unsafe. Consider using _ui64toa_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS." " See online help for details.")) char *__cdecl _ui64toa(unsigned __int64 _Val, char * _DstBuf, int _Radix); 
__declspec(dllimport) __int64 __cdecl _atoi64(const char * _String); 
__declspec(dllimport) __int64 __cdecl _atoi64_l(const char * _String, _locale_t _Locale); 
__declspec(dllimport) __int64 __cdecl _strtoi64(const char * _String, char ** _EndPtr, int _Radix); 
__declspec(dllimport) __int64 __cdecl _strtoi64_l(const char * _String, char ** _EndPtr, int _Radix, _locale_t _Locale); 
__declspec(dllimport) unsigned __int64 __cdecl _strtoui64(const char * _String, char ** _EndPtr, int _Radix); 
__declspec(dllimport) unsigned __int64 __cdecl _strtoui64_l(const char * _String, char ** _EndPtr, int _Radix, _locale_t _Locale); 
__declspec(dllimport) ldiv_t __cdecl ldiv(long _Numerator, long _Denominator); 
__declspec(dllimport) lldiv_t __cdecl lldiv(__int64 _Numerator, __int64 _Denominator); 
#line 485
__declspec(dllimport) errno_t __cdecl _ltoa_s(long _Val, char * _DstBuf, size_t _Size, int _Radix); 

__declspec(deprecated("This function or variable may be unsafe. Consider using _ltoa_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. Se" "e online help for details.")) __declspec(dllimport) char *__cdecl _ltoa(long _Value, char * _Dest, int _Radix); 
__declspec(dllimport) int __cdecl mblen(const char * _Ch, size_t _MaxCount); 
__declspec(dllimport) int __cdecl _mblen_l(const char * _Ch, size_t _MaxCount, _locale_t _Locale); 
__declspec(dllimport) size_t __cdecl _mbstrlen(const char * _Str); 
__declspec(dllimport) size_t __cdecl _mbstrlen_l(const char * _Str, _locale_t _Locale); 
__declspec(dllimport) size_t __cdecl _mbstrnlen(const char * _Str, size_t _MaxCount); 
__declspec(dllimport) size_t __cdecl _mbstrnlen_l(const char * _Str, size_t _MaxCount, _locale_t _Locale); 
__declspec(dllimport) int __cdecl mbtowc(wchar_t * _DstCh, const char * _SrcCh, size_t _SrcSizeInBytes); 
__declspec(dllimport) int __cdecl _mbtowc_l(wchar_t * _DstCh, const char * _SrcCh, size_t _SrcSizeInBytes, _locale_t _Locale); 
__declspec(dllimport) errno_t __cdecl mbstowcs_s(size_t * _PtNumOfCharConverted, wchar_t * _DstBuf, size_t _SizeInWords, const char * _SrcBuf, size_t _MaxCount); 

__declspec(deprecated("This function or variable may be unsafe. Consider using mbstowcs_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS." " See online help for details.")) __declspec(dllimport) size_t __cdecl mbstowcs(wchar_t * _Dest, const char * _Source, size_t _MaxCount); 

__declspec(dllimport) errno_t __cdecl _mbstowcs_s_l(size_t * _PtNumOfCharConverted, wchar_t * _DstBuf, size_t _SizeInWords, const char * _SrcBuf, size_t _MaxCount, _locale_t _Locale); 

__declspec(deprecated("This function or variable may be unsafe. Consider using _mbstowcs_s_l instead. To disable deprecation, use _CRT_SECURE_NO_WARNIN" "GS. See online help for details.")) __declspec(dllimport) size_t __cdecl _mbstowcs_l(wchar_t * _Dest, const char * _Source, size_t _MaxCount, _locale_t _Locale); 

__declspec(dllimport) int __cdecl rand(void); 




__declspec(dllimport) int __cdecl _set_error_mode(int _Mode); 

__declspec(dllimport) void __cdecl srand(unsigned _Seed); 
__declspec(dllimport) double __cdecl strtod(const char * _Str, char ** _EndPtr); 
__declspec(dllimport) double __cdecl _strtod_l(const char * _Str, char ** _EndPtr, _locale_t _Locale); 
__declspec(dllimport) long __cdecl strtol(const char * _Str, char ** _EndPtr, int _Radix); 
__declspec(dllimport) long __cdecl _strtol_l(const char * _Str, char ** _EndPtr, int _Radix, _locale_t _Locale); 
__declspec(dllimport) unsigned long __cdecl strtoul(const char * _Str, char ** _EndPtr, int _Radix); 
__declspec(dllimport) unsigned long __cdecl _strtoul_l(const char * _Str, char ** _EndPtr, int _Radix, _locale_t _Locale); 


__declspec(dllimport) int __cdecl system(const char * _Command); 

__declspec(dllimport) errno_t __cdecl _ultoa_s(unsigned long _Val, char * _DstBuf, size_t _Size, int _Radix); 

__declspec(deprecated("This function or variable may be unsafe. Consider using _ultoa_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. S" "ee online help for details.")) __declspec(dllimport) char *__cdecl _ultoa(unsigned long _Value, char * _Dest, int _Radix); 
__declspec(dllimport) __declspec(deprecated("This function or variable may be unsafe. Consider using wctomb_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. S" "ee online help for details.")) int __cdecl wctomb(char * _MbCh, wchar_t _WCh); 
__declspec(dllimport) __declspec(deprecated("This function or variable may be unsafe. Consider using _wctomb_s_l instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS" ". See online help for details.")) int __cdecl _wctomb_l(char * _MbCh, wchar_t _WCh, _locale_t _Locale); 

__declspec(dllimport) errno_t __cdecl wctomb_s(int * _SizeConverted, char * _MbCh, rsize_t _SizeInBytes, wchar_t _WCh); 

__declspec(dllimport) errno_t __cdecl _wctomb_s_l(int * _SizeConverted, char * _MbCh, size_t _SizeInBytes, wchar_t _WCh, _locale_t _Locale); 
__declspec(dllimport) errno_t __cdecl wcstombs_s(size_t * _PtNumOfCharConverted, char * _Dst, size_t _DstSizeInBytes, const wchar_t * _Src, size_t _MaxCountInBytes); 

__declspec(deprecated("This function or variable may be unsafe. Consider using wcstombs_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS." " See online help for details.")) __declspec(dllimport) size_t __cdecl wcstombs(char * _Dest, const wchar_t * _Source, size_t _MaxCount); 
__declspec(dllimport) errno_t __cdecl _wcstombs_s_l(size_t * _PtNumOfCharConverted, char * _Dst, size_t _DstSizeInBytes, const wchar_t * _Src, size_t _MaxCountInBytes, _locale_t _Locale); 

__declspec(deprecated("This function or variable may be unsafe. Consider using _wcstombs_s_l instead. To disable deprecation, use _CRT_SECURE_NO_WARNIN" "GS. See online help for details.")) __declspec(dllimport) size_t __cdecl _wcstombs_l(char * _Dest, const wchar_t * _Source, size_t _MaxCount, _locale_t _Locale); 
#line 598
__declspec(dllimport) __declspec(noalias) __declspec(restrict) void *__cdecl calloc(size_t _Count, size_t _Size); 
__declspec(dllimport) __declspec(noalias) void __cdecl free(void * _Memory); 
__declspec(dllimport) __declspec(noalias) __declspec(restrict) void *__cdecl malloc(size_t _Size); 

__declspec(dllimport) __declspec(noalias) __declspec(restrict) void *__cdecl realloc(void * _Memory, size_t _NewSize); 

__declspec(dllimport) __declspec(noalias) __declspec(restrict) void *__cdecl _recalloc(void * _Memory, size_t _Count, size_t _Size); 
__declspec(dllimport) __declspec(noalias) void __cdecl _aligned_free(void * _Memory); 
__declspec(dllimport) __declspec(noalias) __declspec(restrict) void *__cdecl _aligned_malloc(size_t _Size, size_t _Alignment); 
__declspec(dllimport) __declspec(noalias) __declspec(restrict) void *__cdecl _aligned_offset_malloc(size_t _Size, size_t _Alignment, size_t _Offset); 

__declspec(dllimport) __declspec(noalias) __declspec(restrict) void *__cdecl _aligned_realloc(void * _Memory, size_t _NewSize, size_t _Alignment); 

__declspec(dllimport) __declspec(noalias) __declspec(restrict) void *__cdecl _aligned_recalloc(void * _Memory, size_t _Count, size_t _Size, size_t _Alignment); 

__declspec(dllimport) __declspec(noalias) __declspec(restrict) void *__cdecl _aligned_offset_realloc(void * _Memory, size_t _NewSize, size_t _Alignment, size_t _Offset); 

__declspec(dllimport) __declspec(noalias) __declspec(restrict) void *__cdecl _aligned_offset_recalloc(void * _Memory, size_t _Count, size_t _Size, size_t _Alignment, size_t _Offset); 
__declspec(dllimport) size_t __cdecl _aligned_msize(void * _Memory, size_t _Alignment, size_t _Offset); 
#line 643
__declspec(dllimport) errno_t __cdecl _itow_s(int _Val, wchar_t * _DstBuf, size_t _SizeInWords, int _Radix); 

__declspec(deprecated("This function or variable may be unsafe. Consider using _itow_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. Se" "e online help for details.")) __declspec(dllimport) wchar_t *__cdecl _itow(int _Value, wchar_t * _Dest, int _Radix); 
__declspec(dllimport) errno_t __cdecl _ltow_s(long _Val, wchar_t * _DstBuf, size_t _SizeInWords, int _Radix); 

__declspec(deprecated("This function or variable may be unsafe. Consider using _ltow_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. Se" "e online help for details.")) __declspec(dllimport) wchar_t *__cdecl _ltow(long _Value, wchar_t * _Dest, int _Radix); 
__declspec(dllimport) errno_t __cdecl _ultow_s(unsigned long _Val, wchar_t * _DstBuf, size_t _SizeInWords, int _Radix); 

__declspec(deprecated("This function or variable may be unsafe. Consider using _ultow_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. S" "ee online help for details.")) __declspec(dllimport) wchar_t *__cdecl _ultow(unsigned long _Value, wchar_t * _Dest, int _Radix); 
__declspec(dllimport) double __cdecl wcstod(const wchar_t * _Str, wchar_t ** _EndPtr); 
__declspec(dllimport) double __cdecl _wcstod_l(const wchar_t * _Str, wchar_t ** _EndPtr, _locale_t _Locale); 
__declspec(dllimport) long __cdecl wcstol(const wchar_t * _Str, wchar_t ** _EndPtr, int _Radix); 
__declspec(dllimport) long __cdecl _wcstol_l(const wchar_t * _Str, wchar_t ** _EndPtr, int _Radix, _locale_t _Locale); 
__declspec(dllimport) unsigned long __cdecl wcstoul(const wchar_t * _Str, wchar_t ** _EndPtr, int _Radix); 
__declspec(dllimport) unsigned long __cdecl _wcstoul_l(const wchar_t * _Str, wchar_t ** _EndPtr, int _Radix, _locale_t _Locale); 
__declspec(dllimport) __declspec(deprecated("This function or variable may be unsafe. Consider using _wdupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS." " See online help for details.")) wchar_t *__cdecl _wgetenv(const wchar_t * _VarName); 
__declspec(dllimport) errno_t __cdecl _wgetenv_s(size_t * _ReturnSize, wchar_t * _DstBuf, size_t _DstSizeInWords, const wchar_t * _VarName); 
#line 667
__declspec(dllimport) errno_t __cdecl _wdupenv_s(wchar_t ** _Buffer, size_t * _BufferSizeInWords, const wchar_t * _VarName); 
#line 675
__declspec(dllimport) int __cdecl _wsystem(const wchar_t * _Command); 

__declspec(dllimport) double __cdecl _wtof(const wchar_t * _Str); 
__declspec(dllimport) double __cdecl _wtof_l(const wchar_t * _Str, _locale_t _Locale); 
__declspec(dllimport) int __cdecl _wtoi(const wchar_t * _Str); 
__declspec(dllimport) int __cdecl _wtoi_l(const wchar_t * _Str, _locale_t _Locale); 
__declspec(dllimport) long __cdecl _wtol(const wchar_t * _Str); 
__declspec(dllimport) long __cdecl _wtol_l(const wchar_t * _Str, _locale_t _Locale); 

__declspec(dllimport) errno_t __cdecl _i64tow_s(__int64 _Val, wchar_t * _DstBuf, size_t _SizeInWords, int _Radix); 
__declspec(dllimport) __declspec(deprecated("This function or variable may be unsafe. Consider using _i64tow_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. " "See online help for details.")) wchar_t *__cdecl _i64tow(__int64 _Val, wchar_t * _DstBuf, int _Radix); 
__declspec(dllimport) errno_t __cdecl _ui64tow_s(unsigned __int64 _Val, wchar_t * _DstBuf, size_t _SizeInWords, int _Radix); 
__declspec(dllimport) __declspec(deprecated("This function or variable may be unsafe. Consider using _ui64tow_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS." " See online help for details.")) wchar_t *__cdecl _ui64tow(unsigned __int64 _Val, wchar_t * _DstBuf, int _Radix); 
__declspec(dllimport) __int64 __cdecl _wtoi64(const wchar_t * _Str); 
__declspec(dllimport) __int64 __cdecl _wtoi64_l(const wchar_t * _Str, _locale_t _Locale); 
__declspec(dllimport) __int64 __cdecl _wcstoi64(const wchar_t * _Str, wchar_t ** _EndPtr, int _Radix); 
__declspec(dllimport) __int64 __cdecl _wcstoi64_l(const wchar_t * _Str, wchar_t ** _EndPtr, int _Radix, _locale_t _Locale); 
__declspec(dllimport) unsigned __int64 __cdecl _wcstoui64(const wchar_t * _Str, wchar_t ** _EndPtr, int _Radix); 
__declspec(dllimport) unsigned __int64 __cdecl _wcstoui64_l(const wchar_t * _Str, wchar_t ** _EndPtr, int _Radix, _locale_t _Locale); 
#line 713
__declspec(dllimport) char *__cdecl _fullpath(char * _FullPath, const char * _Path, size_t _SizeInBytes); 
#line 721
__declspec(dllimport) errno_t __cdecl _ecvt_s(char * _DstBuf, size_t _Size, double _Val, int _NumOfDights, int * _PtDec, int * _PtSign); 

__declspec(dllimport) __declspec(deprecated("This function or variable may be unsafe. Consider using _ecvt_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. Se" "e online help for details.")) char *__cdecl _ecvt(double _Val, int _NumOfDigits, int * _PtDec, int * _PtSign); 
__declspec(dllimport) errno_t __cdecl _fcvt_s(char * _DstBuf, size_t _Size, double _Val, int _NumOfDec, int * _PtDec, int * _PtSign); 

__declspec(dllimport) __declspec(deprecated("This function or variable may be unsafe. Consider using _fcvt_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. Se" "e online help for details.")) char *__cdecl _fcvt(double _Val, int _NumOfDec, int * _PtDec, int * _PtSign); 
__declspec(dllimport) errno_t __cdecl _gcvt_s(char * _DstBuf, size_t _Size, double _Val, int _NumOfDigits); 

__declspec(dllimport) __declspec(deprecated("This function or variable may be unsafe. Consider using _gcvt_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. Se" "e online help for details.")) char *__cdecl _gcvt(double _Val, int _NumOfDigits, char * _DstBuf); 

__declspec(dllimport) int __cdecl _atodbl(_CRT_DOUBLE * _Result, char * _Str); 
__declspec(dllimport) int __cdecl _atoldbl(_LDOUBLE * _Result, char * _Str); 
__declspec(dllimport) int __cdecl _atoflt(_CRT_FLOAT * _Result, char * _Str); 
__declspec(dllimport) int __cdecl _atodbl_l(_CRT_DOUBLE * _Result, char * _Str, _locale_t _Locale); 
__declspec(dllimport) int __cdecl _atoldbl_l(_LDOUBLE * _Result, char * _Str, _locale_t _Locale); 
__declspec(dllimport) int __cdecl _atoflt_l(_CRT_FLOAT * _Result, char * _Str, _locale_t _Locale); 
unsigned long __cdecl _lrotl(unsigned long _Val, int _Shift); 
unsigned long __cdecl _lrotr(unsigned long _Val, int _Shift); 
__declspec(dllimport) errno_t __cdecl _makepath_s(char * _PathResult, size_t _SizeInWords, const char * _Drive, const char * _Dir, const char * _Filename, const char * _Ext); 


__declspec(deprecated("This function or variable may be unsafe. Consider using _makepath_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS" ". See online help for details.")) __declspec(dllimport) void __cdecl _makepath(char * _Path, const char * _Drive, const char * _Dir, const char * _Filename, const char * _Ext); 
#line 769
_onexit_t __cdecl _onexit(_onexit_t _Func); 




__declspec(dllimport) void __cdecl perror(const char * _ErrMsg); 


/* Removed pragma: #pragma warning (push)*/
/* Removed pragma: #pragma warning (disable:6540)*/
__declspec(dllimport) int __cdecl _putenv(const char * _EnvString); 
__declspec(dllimport) errno_t __cdecl _putenv_s(const char * _Name, const char * _Value); 
unsigned __cdecl _rotl(unsigned _Val, int _Shift); 
unsigned __int64 __cdecl _rotl64(unsigned __int64 _Val, int _Shift); 
unsigned __cdecl _rotr(unsigned _Val, int _Shift); 
unsigned __int64 __cdecl _rotr64(unsigned __int64 _Val, int _Shift); 
/* Removed pragma: #pragma warning (pop)*/

__declspec(dllimport) errno_t __cdecl _searchenv_s(const char * _Filename, const char * _EnvVar, char * _ResultPath, size_t _SizeInBytes); 

__declspec(deprecated("This function or variable may be unsafe. Consider using _searchenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNING" "S. See online help for details.")) __declspec(dllimport) void __cdecl _searchenv(const char * _Filename, const char * _EnvVar, char * _ResultPath); 

__declspec(deprecated("This function or variable may be unsafe. Consider using _splitpath_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNING" "S. See online help for details.")) __declspec(dllimport) void __cdecl _splitpath(const char * _FullPath, char * _Drive, char * _Dir, char * _Filename, char * _Ext); 
__declspec(dllimport) errno_t __cdecl _splitpath_s(const char * _FullPath, char * _Drive, size_t _DriveSize, char * _Dir, size_t _DirSize, char * _Filename, size_t _FilenameSize, char * _Ext, size_t _ExtSize); 
#line 799
__declspec(dllimport) void __cdecl _swab(char * _Buf1, char * _Buf2, int _SizeInBytes); 
#line 810
__declspec(dllimport) wchar_t *__cdecl _wfullpath(wchar_t * _FullPath, const wchar_t * _Path, size_t _SizeInWords); 
#line 816
__declspec(dllimport) errno_t __cdecl _wmakepath_s(wchar_t * _PathResult, size_t _SIZE, const wchar_t * _Drive, const wchar_t * _Dir, const wchar_t * _Filename, const wchar_t * _Ext); 


__declspec(deprecated("This function or variable may be unsafe. Consider using _wmakepath_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNING" "S. See online help for details.")) __declspec(dllimport) void __cdecl _wmakepath(wchar_t * _ResultPath, const wchar_t * _Drive, const wchar_t * _Dir, const wchar_t * _Filename, const wchar_t * _Ext); 


__declspec(dllimport) void __cdecl _wperror(const wchar_t * _ErrMsg); 

__declspec(dllimport) int __cdecl _wputenv(const wchar_t * _EnvString); 
__declspec(dllimport) errno_t __cdecl _wputenv_s(const wchar_t * _Name, const wchar_t * _Value); 
__declspec(dllimport) errno_t __cdecl _wsearchenv_s(const wchar_t * _Filename, const wchar_t * _EnvVar, wchar_t * _ResultPath, size_t _SizeInWords); 

__declspec(deprecated("This function or variable may be unsafe. Consider using _wsearchenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNIN" "GS. See online help for details.")) __declspec(dllimport) void __cdecl _wsearchenv(const wchar_t * _Filename, const wchar_t * _EnvVar, wchar_t * _ResultPath); 
__declspec(deprecated("This function or variable may be unsafe. Consider using _wsplitpath_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNIN" "GS. See online help for details.")) __declspec(dllimport) void __cdecl _wsplitpath(const wchar_t * _FullPath, wchar_t * _Drive, wchar_t * _Dir, wchar_t * _Filename, wchar_t * _Ext); 
__declspec(dllimport) errno_t __cdecl _wsplitpath_s(const wchar_t * _FullPath, wchar_t * _Drive, size_t _DriveSize, wchar_t * _Dir, size_t _DirSize, wchar_t * _Filename, size_t _FilenameSize, wchar_t * _Ext, size_t _ExtSize); 
#line 841
__declspec(deprecated("This function or variable has been superceded by newer library or operating system functionality. Consider using SetErrorMode in" "stead. See online help for details.")) __declspec(dllimport) void __cdecl _seterrormode(int _Mode); 
__declspec(deprecated("This function or variable has been superceded by newer library or operating system functionality. Consider using Beep instead. S" "ee online help for details.")) __declspec(dllimport) void __cdecl _beep(unsigned _Frequency, unsigned _Duration); 
__declspec(deprecated("This function or variable has been superceded by newer library or operating system functionality. Consider using Sleep instead. " "See online help for details.")) __declspec(dllimport) void __cdecl _sleep(unsigned long _Duration); 
#line 862
/* Removed pragma: #pragma warning(push)*/
/* Removed pragma: #pragma warning(disable: 4141)*/
__declspec(deprecated("The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _ecvt. See online help for details.")) __declspec(deprecated("This function or variable may be unsafe. Consider using _ecvt_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. Se" "e online help for details.")) __declspec(dllimport) char *__cdecl ecvt(double _Val, int _NumOfDigits, int * _PtDec, int * _PtSign); 
__declspec(deprecated("The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _fcvt. See online help for details.")) __declspec(deprecated("This function or variable may be unsafe. Consider using _fcvt_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. Se" "e online help for details.")) __declspec(dllimport) char *__cdecl fcvt(double _Val, int _NumOfDec, int * _PtDec, int * _PtSign); 
__declspec(deprecated("The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _gcvt. See online help for details.")) __declspec(deprecated("This function or variable may be unsafe. Consider using _fcvt_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. Se" "e online help for details.")) __declspec(dllimport) char *__cdecl gcvt(double _Val, int _NumOfDigits, char * _DstBuf); 
__declspec(deprecated("The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _itoa. See online help for details.")) __declspec(deprecated("This function or variable may be unsafe. Consider using _itoa_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. Se" "e online help for details.")) __declspec(dllimport) char *__cdecl itoa(int _Val, char * _DstBuf, int _Radix); 
__declspec(deprecated("The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _ltoa. See online help for details.")) __declspec(deprecated("This function or variable may be unsafe. Consider using _ltoa_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. Se" "e online help for details.")) __declspec(dllimport) char *__cdecl ltoa(long _Val, char * _DstBuf, int _Radix); 
__declspec(deprecated("The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _putenv. See online help for details.")) __declspec(dllimport) int __cdecl putenv(const char * _EnvString); 
__declspec(deprecated("The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _swab. See online help for details.")) __declspec(dllimport) void __cdecl swab(char * _Buf1, char * _Buf2, int _SizeInBytes); 
__declspec(deprecated("The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _ultoa. See online help for details.")) __declspec(deprecated("This function or variable may be unsafe. Consider using _ultoa_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. S" "ee online help for details.")) __declspec(dllimport) char *__cdecl ultoa(unsigned long _Val, char * _Dstbuf, int _Radix); 
/* Removed pragma: #pragma warning(pop)*/
_onexit_t __cdecl onexit(_onexit_t _Func); 
#line 884
#pragma pack ( pop )
#line 28 "C:\\Program Files (x86)\\Parasoft\\C++test for Visual Studio\\9.2\\engine\\runtime\\include\\cpptest_common.h"
typedef 
#line 21
struct { 

char *ptr; 

size_t len; 

size_t size; 
} CppTestExpandableString; 
#line 37
typedef 
#line 30
struct CppTestListElement_s { 

char *data; 

struct CppTestListElement_s *next; 

struct CppTestListElement_s *prev; 
} CppTestListElement; 
#line 44
typedef 
#line 39
struct { 

CppTestListElement *head; 

CppTestListElement *tail; 
} CppTestList; 

typedef CppTestListElement *CppTestListIterator; 
typedef const CppTestListElement *CppTestListConstIterator; 

typedef unsigned long CppTest_ULong; 



typedef wchar_t CppTest_wchar_t; 



__declspec(dllimport) extern void __cdecl cpptestExpandableStringInit(CppTestExpandableString * es, size_t initSize); 



__declspec(dllimport) extern void __cdecl cpptestExpandableStringExpand(CppTestExpandableString * es); 



__declspec(dllimport) extern void __cdecl cpptestExpandableStringAppend(CppTestExpandableString * es, const char * str, size_t len); 



__declspec(dllimport) extern void __cdecl cpptestExpandableStringAppendChar(CppTestExpandableString * es, char c); 



__declspec(dllimport) extern void __cdecl cpptestExpandableStringDispose(CppTestExpandableString * es); 



__declspec(dllimport) extern void __cdecl cpptestListInit(CppTestList * l); 


typedef void (__cdecl *ListElementDestructor)(char * data, void * additionalParameter); 



__declspec(dllimport) extern void __cdecl cpptestListClear(CppTestList * l, ListElementDestructor destructor, void * additionalParameter); 


__declspec(dllimport) extern CppTestListIterator __cdecl cpptestListRemove(CppTestList * l, CppTestListIterator it); 


__declspec(dllimport) extern void __cdecl cpptestListPushFront(CppTestList * l, char * data); 


__declspec(dllimport) extern char *__cdecl cpptestListFrontElement(const CppTestList * l); 


__declspec(dllimport) extern void __cdecl cpptestListPushBack(CppTestList * l, char * data); 


__declspec(dllimport) extern CppTestListIterator __cdecl cpptestListGetIterator(const CppTestList * l); 


__declspec(dllimport) extern char *__cdecl cpptestListIteratorElement(CppTestListConstIterator it); 


__declspec(dllimport) extern CppTestListIterator __cdecl cpptestListIteratorNext(CppTestListConstIterator it); 


__declspec(dllimport) extern int __cdecl cpptestListIteratorEnd(CppTestListConstIterator it); 


__declspec(dllimport) extern char *__cdecl cpptestStrDup(const char * str); 


__declspec(dllimport) extern unsigned __cdecl cpptestStrLen(const char * str); 


__declspec(dllimport) extern int __cdecl cpptestStrCmp(const char * str1, const char * str2); 


__declspec(dllimport) extern int __cdecl cpptestStrNCmp(const char * str1, const char * str2, unsigned n); 


__declspec(dllimport) extern int __cdecl cpptestStrCaseCmp(const char * str1, const char * str2); 


__declspec(dllimport) extern int __cdecl cpptestStrNCaseCmp(const char * str1, const char * str2, unsigned n); 


__declspec(dllimport) extern unsigned __cdecl cpptestCharToDigit(char c); 


__declspec(dllimport) extern const char *__cdecl cpptestStrToInteger(const char * str, __int64 * integer); 


__declspec(dllimport) extern const char *__cdecl cpptestStrToUInteger(const char * str, unsigned __int64 * uinteger); 


__declspec(dllimport) extern const char *__cdecl cpptestStrToBool(const char * str, int * result); 


__declspec(dllimport) extern char *__cdecl cpptestAllocateString(size_t size, unsigned char content); 



__declspec(dllimport) extern CppTest_wchar_t *__cdecl cpptestWStrDup(const CppTest_wchar_t * str); 


__declspec(dllimport) extern unsigned __cdecl cpptestWStrLen(const CppTest_wchar_t * str); 


__declspec(dllimport) extern int __cdecl cpptestWStrCmp(const CppTest_wchar_t * str1, const CppTest_wchar_t * str2); 


__declspec(dllimport) extern int __cdecl cpptestWStrNCmp(const CppTest_wchar_t * str1, const CppTest_wchar_t * str2, unsigned n); 


__declspec(dllimport) extern unsigned __cdecl cpptestWCharToDigit(CppTest_wchar_t c); 


__declspec(dllimport) extern const CppTest_wchar_t *__cdecl cpptestWStrToInteger(const CppTest_wchar_t * str, __int64 * integer); 


__declspec(dllimport) extern const CppTest_wchar_t *__cdecl cpptestWStrToUInteger(const CppTest_wchar_t * str, unsigned __int64 * uinteger); 
#line 169
__declspec(dllimport) extern void *__cdecl cpptestMalloc(size_t size); 


__declspec(dllimport) extern void *__cdecl cpptestAlloc(size_t size); 


__declspec(dllimport) extern void __cdecl cpptestFree(void * str); 


__declspec(dllimport) extern void *__cdecl cpptestMemset(void * ptr, int c, size_t size); 
#line 193
typedef struct CppTestTreeNode *CppTestTree; 
#line 199
__declspec(dllimport) extern void __cdecl cpptestTreeInit(CppTestTree * tree); 
#line 205
__declspec(dllimport) extern void __cdecl cpptestTreeClear(CppTestTree * tree); 
#line 212
__declspec(dllimport) extern int __cdecl cpptestTreeFind(CppTestTree * tree, const char * key, void ** ret); 
#line 218
__declspec(dllimport) extern void __cdecl cpptestTreeAdd(CppTestTree * tree, const char * key, void * value); 

typedef void __cdecl CppTestTreeCallBackRoutine(const char * key, void * value); 
typedef CppTestTreeCallBackRoutine *CppTestTreeCallBack; 
#line 227
__declspec(dllimport) extern void __cdecl cpptestTreeTraverseInorder(const CppTestTree * tree, const CppTestTreeCallBack callback); 
#line 235
__declspec(dllimport) extern void __cdecl cpptestAddProperty(const char * name, const char * value); 
#line 243
__declspec(dllimport) extern void __cdecl cpptestAddWeakProperty(const char * name, const char * value); 
#line 256
__declspec(dllimport) extern void __cdecl cpptestParseAndAddProperties(char * properties); 
#line 262
__declspec(dllimport) extern int __cdecl cpptestHasProperty(const char * name); 
#line 269
__declspec(dllimport) extern const char *__cdecl cpptestGetProperty(const char * name); 
#line 276
__declspec(dllimport) extern const char *__cdecl cpptestGetPropertyEx(const char * name, const char * defaultValue); 
#line 283
__declspec(dllimport) extern __int64 __cdecl cpptestGetIntProperty(const char * name); 
#line 290
__declspec(dllimport) extern __int64 __cdecl cpptestGetIntPropertyEx(const char * name, __int64 defaultValue); 
#line 297
__declspec(dllimport) extern unsigned __int64 __cdecl cpptestGetUIntProperty(const char * name); 
#line 304
__declspec(dllimport) extern unsigned __int64 __cdecl cpptestGetUIntPropertyEx(const char * name, unsigned __int64 defaultValue); 
#line 311
__declspec(dllimport) extern int __cdecl cpptestGetBoolProperty(const char * name); 
#line 318
__declspec(dllimport) extern int __cdecl cpptestGetBoolPropertyEx(const char * name, int defaultValue); 
#line 324
__declspec(dllimport) extern const char *__cdecl cpptestPathRelativeToAbsolute(const char * relPath, const char * relToFileName); 
#line 21 "C:\\Program Files (x86)\\Parasoft\\C++test for Visual Studio\\9.2\\engine\\runtime\\include\\cpptest_system.h"
typedef 
#line 15
struct { 
void *(*mallocFunc)(size_t size); 
void *(*callocFunc)(size_t elements, size_t elem_size); 
void *(*reallocFunc)(void * ptr, size_t new_size); 
void (*freeFunc)(void * ptr); 
void *(*memsetFunc)(void * ptr, int value, size_t size); 
} CppTest_System; 
#line 166 "C:\\Program Files (x86)\\Parasoft\\C++test for Visual Studio\\9.2\\engine\\runtime\\include\\cpptest_runtime_u.h"
typedef unsigned CppTest_ErrorCode; 



typedef void (*__CPTR_TestCasePtr)(void); 


typedef void (*__CPTR_TestCaseBreakFuncPtr)(void); 

struct _CONTEXT; 
struct _EXCEPTION_RECORD; 

struct CppTest_DataSource; 
#line 194
__declspec(dllimport) extern const char *__cdecl cpptestGetCurrentTestCaseName(void); 
#line 200
__declspec(dllimport) extern const char *__cdecl cpptestGetCurrentTestSuiteName(void); 
#line 206
__declspec(dllimport) extern unsigned __cdecl cpptestGetCurrentTestCaseIteration(void); 
#line 220
__declspec(dllimport) extern const char *__cdecl cpptestGetCurrentTestCaseFile(void); 
#line 226
__declspec(dllimport) extern unsigned __cdecl cpptestGetCurrentTestCaseLine(void); 
#line 233
__declspec(dllimport) extern void __cdecl cpptestCommunicationBegin(void); 


__declspec(dllimport) extern void __cdecl cpptestCommunicationEnd(void); 


__declspec(dllimport) extern void __cdecl cpptestTestRunnerBegin(void); 


__declspec(dllimport) extern void __cdecl cpptestTestRunnerEnd(void); 


__declspec(dllimport) extern void __cdecl cpptestTestSuiteBegin(const char * name, const char * file, unsigned line); 



__declspec(dllimport) extern void __cdecl cpptestTestSuiteEnd(void); 


__declspec(dllimport) extern void __cdecl cpptestTestCaseBegin(const char * name, CppTest_ErrorCode expectedErrorCode, unsigned expectedErrorCodeMask, int isCpp, const char * file, unsigned line); 




__declspec(dllimport) extern void __cdecl cpptestTestCaseEnd(void); 


__declspec(dllimport) extern void __cdecl cpptestDsForCurrentTestCaseInitialized(struct CppTest_DataSource * dataSource); 


__declspec(dllimport) extern void __cdecl cpptestDsTestCaseBegin(const char * name, CppTest_ErrorCode expectedErrorCode, unsigned expectedErrorCodeMask, int isCpp, const char * file, unsigned line); 


__declspec(dllimport) extern void __cdecl cpptestDsTestCaseEnd(void); 


__declspec(dllimport) extern void __cdecl cpptestDsTestCaseIterationBegin(unsigned iteration, const char * signature); 


__declspec(dllimport) extern void __cdecl cpptestDsTestCaseIterationEnd(void); 
#line 288
__declspec(dllimport) extern const char *__cdecl cpptestFormatBuffer(char * buffer, const char * format, ...); 
#line 297
__declspec(dllimport) extern int __cdecl cpptestCharPtrsEqual(const char * expected, const char * actual); 
#line 308
__declspec(dllimport) extern int __cdecl cpptestWCharPtrsEqual(const void * expected, const void * actual); 




__declspec(dllimport) extern void __cdecl cpptestUnhandledStructuredExceptionInThread(unsigned code); 

__declspec(dllimport) extern int __cdecl cpptestUnhandledStructuredExceptionInTestCase(unsigned code); 

__declspec(dllimport) extern void __cdecl cpptestUnhandledCppExceptionInThread(void); 

__declspec(dllimport) extern void __cdecl cpptestNoExpectedCppExceptionInTestCase(const char * e); 

__declspec(dllimport) extern void __cdecl cpptestUnhandledStdExceptionInTestCase(const char * what); 

__declspec(dllimport) extern void __cdecl cpptestUnhandledCppExceptionInTestCase(void); 
#line 331
__declspec(dllimport) extern void __cdecl cpptestSignalFound(int sigNo); 


__declspec(dllimport) extern __CPTR_TestCaseBreakFuncPtr __cdecl cpptestGetTestCaseBreakFuncPtr(void); 


__declspec(dllimport) extern __CPTR_TestCaseBreakFuncPtr __cdecl cpptestSetTestCaseBreakFuncPtr(__CPTR_TestCaseBreakFuncPtr funcpPtr); 
#line 354
__declspec(dllimport) extern char __cdecl cpptestLimitsGetMaxChar(void); 
#line 360
__declspec(dllimport) extern char __cdecl cpptestLimitsGetMinChar(void); 
#line 366
__declspec(dllimport) extern signed char __cdecl cpptestLimitsGetMaxSignedChar(void); 
#line 372
__declspec(dllimport) extern signed char __cdecl cpptestLimitsGetMinSignedChar(void); 
#line 378
__declspec(dllimport) extern unsigned char __cdecl cpptestLimitsGetMaxUnsignedChar(void); 
#line 385
__declspec(dllimport) extern short __cdecl cpptestLimitsGetMaxShort(void); 
#line 391
__declspec(dllimport) extern short __cdecl cpptestLimitsGetMinShort(void); 
#line 397
__declspec(dllimport) extern unsigned short __cdecl cpptestLimitsGetMaxUnsignedShort(void); 
#line 404
__declspec(dllimport) extern int __cdecl cpptestLimitsGetMaxInt(void); 
#line 410
__declspec(dllimport) extern int __cdecl cpptestLimitsGetMinInt(void); 
#line 416
__declspec(dllimport) extern unsigned __cdecl cpptestLimitsGetMaxUnsignedInt(void); 
#line 423
__declspec(dllimport) extern long __cdecl cpptestLimitsGetMaxLong(void); 
#line 429
__declspec(dllimport) extern long __cdecl cpptestLimitsGetMinLong(void); 
#line 435
__declspec(dllimport) extern unsigned long __cdecl cpptestLimitsGetMaxUnsignedLong(void); 
#line 442
__declspec(dllimport) extern float __cdecl cpptestLimitsGetMaxPosFloat(void); 
#line 448
__declspec(dllimport) extern float __cdecl cpptestLimitsGetMinNegFloat(void); 
#line 454
__declspec(dllimport) extern float __cdecl cpptestLimitsGetMaxNegFloat(void); 
#line 460
__declspec(dllimport) extern float __cdecl cpptestLimitsGetMinPosFloat(void); 
#line 467
__declspec(dllimport) extern double __cdecl cpptestLimitsGetMaxPosDouble(void); 
#line 473
__declspec(dllimport) extern double __cdecl cpptestLimitsGetMinNegDouble(void); 
#line 479
__declspec(dllimport) extern double __cdecl cpptestLimitsGetMaxNegDouble(void); 
#line 485
__declspec(dllimport) extern double __cdecl cpptestLimitsGetMinPosDouble(void); 
#line 492
__declspec(dllimport) extern long double __cdecl cpptestLimitsGetMaxPosLongDouble(void); 
#line 498
__declspec(dllimport) extern long double __cdecl cpptestLimitsGetMinNegLongDouble(void); 
#line 504
__declspec(dllimport) extern long double __cdecl cpptestLimitsGetMaxNegLongDouble(void); 
#line 510
__declspec(dllimport) extern long double __cdecl cpptestLimitsGetMinPosLongDouble(void); 
#line 527
__declspec(dllimport) extern int __cdecl CppTest_IsCurrentTestCase(const char * id); 
#line 533
__declspec(dllimport) extern const char *__cdecl CppTest_GetCurrentTestCaseName(void); 
#line 539
__declspec(dllimport) extern const char *__cdecl CppTest_GetCurrentTestSuiteName(void); 
#line 547
__declspec(dllimport) extern const char *__cdecl CppTest_Format(const char * format, ...); 
#line 553
typedef struct CppTest_StreamRedirectStruct CppTest_StreamRedirect; 
typedef void (*CppTest_ClearFlush)(); 
typedef int (*CppTest_StreamDup)(long, int); 
#line 562
void CppTest_flushStdOutput(void); 
#line 570
void CppTest_flushStdError(void); 
#line 577
void CppTest_clearStdInput(void); 

int CppTest_streamDup(long, int); 
#line 646
__declspec(dllimport) extern CppTest_StreamRedirect *__cdecl CppTest_StreamRedirectInput(int fd, const char * value, CppTest_ClearFlush ptr, CppTest_StreamDup ptr1); 
#line 661
__declspec(dllimport) extern CppTest_StreamRedirect *__cdecl CppTest_StreamRedirectNInput(int fd, const char * value, unsigned size, CppTest_ClearFlush ptr, CppTest_StreamDup ptr1); 
#line 673
__declspec(dllimport) extern CppTest_StreamRedirect *__cdecl CppTest_StreamRedirectOutput(int fd, CppTest_ClearFlush ptr); 
#line 688
__declspec(dllimport) extern int __cdecl CppTest_StreamCompare(CppTest_StreamRedirect * redirect, const char * value); 
#line 706
__declspec(dllimport) extern int __cdecl CppTest_StreamNCompare(CppTest_StreamRedirect * redirect, const char * value, unsigned size); 
#line 719
__declspec(dllimport) extern int __cdecl CppTest_StreamSearch(CppTest_StreamRedirect * redirect, const char * pattern); 
#line 732
__declspec(dllimport) extern int __cdecl CppTest_StreamNSearch(CppTest_StreamRedirect * redirect, const char * pattern, unsigned size); 
#line 746
__declspec(dllimport) extern char *__cdecl CppTest_StreamReadData(CppTest_StreamRedirect * redirect, unsigned * len); 
#line 756
__declspec(dllimport) extern void __cdecl CppTest_StreamReset(CppTest_StreamRedirect * redirect); 
#line 764
__declspec(dllimport) extern void __cdecl CppTest_ClearRedirects(void); 
#line 773
__declspec(dllimport) extern struct CppTest_DataSource *__cdecl cpptestGetCurrentDataSource(void); 
#line 779
__declspec(dllimport) extern void __cdecl cpptestIgnoreCurrStackElement(void); 


typedef void (*CppTestThreadInitCallback)(void); 




__declspec(dllimport) extern void __cdecl cpptestSetThreadInitCallback(CppTestThreadInitCallback callback); 


typedef void (*CppTestPropertiesInitCallback)(void); 




__declspec(dllimport) extern void __cdecl cpptestSetPropertiesInitCallback(CppTestPropertiesInitCallback callback); 
#line 801
__declspec(dllimport) extern void __cdecl cpptestInitializeRuntime(CppTestPropertiesInitCallback propInitCallback, CppTestThreadInitCallback threadInitCallback, CppTest_System * system); 
#line 810
__declspec(dllimport) extern void __cdecl cpptestFinalizeRuntime(void); 
#line 816
typedef 
#line 813
struct { 
long seconds; 
long nanoseconds; 
} CppTest_Time; 
#line 822
__declspec(dllimport) extern void __cdecl cpptestCheckMemoryLeaks(const char * file, unsigned line, int isAssert); 
#line 830
__declspec(dllimport) extern CppTest_Time __cdecl CppTest_TimeInit(long seconds, long nanoseconds); 
#line 837
__declspec(dllimport) extern CppTest_Time __cdecl CppTest_TimeCurrent(void); 




__declspec(dllimport) extern CppTest_Time __cdecl CppTest_TimeDiff(CppTest_Time t1, CppTest_Time t2); 
#line 851
__declspec(dllimport) extern int __cdecl CppTest_TimeCompare(CppTest_Time t1, CppTest_Time t2); 
#line 857
const char *__cdecl CppTestCallProgramWrapper(const char * program, int * pResult, const char * param1, const char * param2, const char * param3); 
#line 864
__declspec(dllimport) extern void __cdecl cpptestUnhandledExceptionTerminate(void); 
#line 871
__declspec(dllimport) extern void __cdecl cpptestAssertException(const char * file, unsigned line, const char * message, const char * arg1, const char * arg2, const char * arg3, const char * arg4, int kind); 


void CppTest_InitializeRuntime(void); 

void CppTest_FinalizeRuntime(void); 

__declspec(dllimport) extern char **__cdecl CppTest_CmdLineToArgv(const char * cmdLine, int * argc); 

__declspec(dllimport) extern void __cdecl CppTest_FreeArgv(int argc, char * argv[]); 



__declspec(dllimport) extern CppTest_wchar_t **__cdecl CppTest_CmdLineToArgvW(const CppTest_wchar_t * cmdLine, int * argc); 

__declspec(dllimport) extern void __cdecl CppTest_FreeArgvW(int argc, CppTest_wchar_t * argv[]); 



extern int CppTest_Main(int argc, char * argv[]); 



extern int CppTest_MainW(int argc, CppTest_wchar_t * argv[]); 



__declspec(dllimport) extern const char *__cdecl cpptestStringPool(int id, const char * str); 

int __cdecl CppTest_IsCurrentContext(const char * context); 


__declspec(dllimport) extern void *__cdecl cpptestDsMalloc(size_t size); 


__declspec(dllimport) extern void __cdecl cpptestDsFree(void * str); 


__declspec(dllimport) extern void __cdecl cpptestDsCsvError(CppTest_ErrorCode errorCode, const char * err, const char * file, unsigned line, unsigned column); 



__declspec(dllimport) extern void __cdecl cpptestDsCsvErrorOpeningFile(const char * err, const char * file); 


__declspec(dllimport) extern void __cdecl cpptestNoDsError(const char * dataSourceName); 


__declspec(dllimport) extern void __cdecl cpptestDsErrorInValue(const char * value); 


__declspec(dllimport) extern void __cdecl cpptestDsUnknownValue(const char * name); 


__declspec(dllimport) extern int __cdecl cpptestDsNotInitialized(void); 


__declspec(dllimport) extern int __cdecl cpptestDsMethodNotInitialized(const char * method); 


__declspec(dllimport) extern void __cdecl cpptestAssertCall(const char * message, const char * file, unsigned line); 


__declspec(dllimport) extern void __cdecl cpptestExitCall(int exitCode); 


__declspec(dllimport) extern void __cdecl cpptestAbortCall(void); 


__declspec(dllimport) extern void __cdecl cpptestRiseCall(int exitCode); 



__declspec(dllimport) extern void __cdecl cpptestInvalidParamCalled(const CppTest_wchar_t * expression, const CppTest_wchar_t * function, const CppTest_wchar_t * file, unsigned line); 




__declspec(dllimport) extern void __cdecl cpptestTooLargeStackTrace(unsigned maxAllowedStackTraceDepth); 



__declspec(dllimport) extern void __cdecl cpptestTestCaseNotValidated(const char * file, unsigned line); 



__declspec(dllimport) extern void __cdecl cpptestReport(const char * txt, const char * file, unsigned line, int reportStackTrace); 


__declspec(dllimport) extern void __cdecl cpptestReportBool(const char * txt, int value, const char * file, unsigned line); 


__declspec(dllimport) extern void __cdecl cpptestReportInteger(const char * txt, __int64 value, const char * file, unsigned line); 


__declspec(dllimport) extern void __cdecl cpptestReportUInteger(const char * txt, unsigned __int64 value, const char * file, unsigned line); 


__declspec(dllimport) extern void __cdecl cpptestReportFloat(const char * txt, double value, const char * file, unsigned line); 


__declspec(dllimport) extern void __cdecl cpptestReportCStr(const char * txt, const char * value, const char * file, unsigned line); 


__declspec(dllimport) extern void __cdecl cpptestReportCStrN(const char * txt, const char * value, unsigned maxSize, const char * file, unsigned line); 


__declspec(dllimport) extern void __cdecl cpptestReportMemBuffer(const char * txt, const void * value, unsigned size, const char * file, unsigned line); 


__declspec(dllimport) extern void __cdecl cpptestReportPtr(const char * txt, int isNull, const char * file, unsigned line); 



__declspec(dllimport) extern void __cdecl cpptestPostConditionBool(const char * valueString, int value, const char * file, unsigned line); 


__declspec(dllimport) extern void __cdecl cpptestPostConditionInteger(const char * valueString, __int64 value, const char * file, unsigned line); 


__declspec(dllimport) extern void __cdecl cpptestPostConditionUInteger(const char * valueString, unsigned __int64 value, const char * file, unsigned line); 


__declspec(dllimport) extern void __cdecl cpptestPostConditionFloat(const char * valueString, double value, const char * file, unsigned line); 


__declspec(dllimport) extern void __cdecl cpptestPostConditionCStr(const char * valueString, const char * value, const char * file, unsigned line); 


__declspec(dllimport) extern void __cdecl cpptestPostConditionCStrN(const char * valueString, const char * value, unsigned maxSize, const char * file, unsigned line); 


__declspec(dllimport) extern void __cdecl cpptestPostConditionMemBuffer(const char * valueString, const void * value, unsigned size, const char * file, unsigned line); 


__declspec(dllimport) extern void __cdecl cpptestPostConditionPtr(const char * valueString, int isNull, const char * file, unsigned line); 


__declspec(dllimport) extern void __cdecl cpptestPostConditionExternal(const char * userMessage, const char * ret, const char * file, unsigned line); 


__declspec(dllimport) extern void __cdecl cpptestExternalProcessError(CppTest_ErrorCode errorCode, const char * err); 


__declspec(dllimport) extern void __cdecl cpptestExternalProcessErrorFull(CppTest_ErrorCode errorCode, const char * err, const char * program, const char * param1, const char * param2, const char * param3); 
#line 1021
__declspec(dllimport) extern int __cdecl cpptestAssertion(int value, const char * userMessage, const char * conditionStr, const char * file, unsigned line); 


__declspec(dllimport) extern int __cdecl cpptestEqualAssertion(int value, const char * userMessage, const char * expectedStr, const char * actualStr, const char * file, unsigned line); 



__declspec(dllimport) extern int __cdecl cpptestBoolEqualAssertion(int value, int expected, int actual, const char * userMessage, const char * expectedStr, const char * actualStr, const char * file, unsigned line); 



__declspec(dllimport) extern int __cdecl cpptestIntegerEqualAssertion(int value, __int64 expected, __int64 actual, int hasDelta, __int64 delta, unsigned * arrayIndex, const char * userMessage, const char * expectedStr, const char * actualStr, const char * file, unsigned line); 




__declspec(dllimport) extern int __cdecl cpptestUIntegerEqualAssertion(int value, unsigned __int64 expected, unsigned __int64 actual, int hasDelta, unsigned __int64 delta, unsigned * arrayIndex, const char * userMessage, const char * expectedStr, const char * actualStr, const char * file, unsigned line); 




__declspec(dllimport) extern int __cdecl cpptestFloatEqualAssertion(int value, double expected, double actual, int hasDelta, double delta, unsigned * arrayIndex, const char * userMessage, const char * expectedStr, const char * actualStr, const char * file, unsigned line); 




__declspec(dllimport) extern int __cdecl cpptestFloatFmtEqualAssertion(int value, double actual, const char * userMessage, const char * expectedStr, const char * actualStr, const char * file, unsigned line); 



__declspec(dllimport) extern int __cdecl cpptestCstrEqualAssertion(int value, const char * expected, const char * actual, unsigned * arrayIndex, const char * userMessage, const char * expectedStr, const char * actualStr, const char * file, unsigned line); 



__declspec(dllimport) extern int __cdecl cpptestCstrNEqualAssertion(int value, const char * expected, const char * actual, unsigned maxSize, const char * userMessage, const char * expectedStr, const char * actualStr, const char * file, unsigned line); 



__declspec(dllimport) extern int __cdecl cpptestMemBufferEqualAssertion(int value, const void * expected, const void * actual, unsigned size, const char * userMessage, const char * expectedStr, const char * actualStr, const char * file, unsigned line); 




__declspec(dllimport) extern int __cdecl cpptestPtrEqualAssertion(int value, const void * expected, const void * actual, unsigned * arrayIndex, const char * userMessage, const char * expectedStr, const char * actualStr, const char * file, unsigned line); 
#line 1070
__declspec(dllimport) extern int __cdecl cpptestWCstrEqualAssertion(int value, const CppTest_wchar_t * expected, const CppTest_wchar_t * actual, unsigned * arrayIndex, const char * userMessage, const char * expectedStr, const char * actualStr, const char * file, unsigned line); 
#line 1076
__declspec(dllimport) extern void __cdecl cpptestThrowAssertion(int value, const char * userMessage, const char * exceptionTypeStr, const char * file, unsigned line); 


__declspec(dllimport) extern void __cdecl cpptestNoThrowAssertion(int value, const char * userMessage, const char * file, unsigned line); 


__declspec(dllimport) extern void __cdecl cpptestNoExpectedExceptionInTestCase(const char * e); 


__declspec(dllimport) extern void __cdecl cpptestStdExceptionInTestCase(const char * what); 


__declspec(dllimport) extern void __cdecl cpptestExceptionInTestCase(void); 


__declspec(dllimport) extern void __cdecl cpptestTestCaseDisabled(const char * name, const char * file, unsigned line); 



__declspec(dllimport) extern int __cdecl cpptestCharPtrsNEqual(const char * expected, const char * actual, unsigned maxSize); 


__declspec(dllimport) extern int __cdecl cpptestMemBuffersEqual(const void * expected, const void * actual, unsigned size); 


__declspec(dllimport) extern int __cdecl cpptestFloatsFmtEqual(const char * expected, double actual); 


__declspec(dllimport) extern void __cdecl cpptestTimeout(unsigned long timeout); 


__declspec(dllimport) extern void __cdecl cpptestUserBreak(const char * file, unsigned line); 

void __cdecl cpptestTestCaseSlave(__CPTR_TestCasePtr tc); 
#line 41 "C:\\Program Files (x86)\\Parasoft\\C++test for Visual Studio\\9.2\\engine\\runtime\\include\\cpptest_data_source.h"
typedef 
#line 16
struct CppTest_DataSource { 

const char *(*getMemBuffer)(struct CppTest_DataSource *, const char * name, unsigned * size); 
const char *(*getCStr)(struct CppTest_DataSource *, const char * name); 

const CppTest_wchar_t *(*getWCStr)(struct CppTest_DataSource *, const char * name); 

__int64 (*getInteger)(struct CppTest_DataSource *, const char * name); 
unsigned __int64 (*getUInteger)(struct CppTest_DataSource *, const char * name); 
double (*getFloat)(struct CppTest_DataSource *, const char * name); 
int (*getBool)(struct CppTest_DataSource *, const char * name); 
char (*getChar)(struct CppTest_DataSource *, const char * name); 

int (*hasColumn)(struct CppTest_DataSource *, const char * name); 

int (*loadNextData)(struct CppTest_DataSource *); 
int (*hasMoreData)(struct CppTest_DataSource *); 
unsigned (*getIteration)(struct CppTest_DataSource *); 




void (*finalize)(struct CppTest_DataSource *); 

void *data; 
} CppTest_DataSource; 

typedef CppTest_DataSource *(*CppTest_GetDataSourceFPtr)(const char * dataSource, const char * testSuite); 
#line 52
extern CppTest_DataSource *__cdecl CppTest_DsArray(const char ** data, int rows, int columns); 
extern CppTest_DataSource *__cdecl CppTest_DsRepeat(int count); 
extern CppTest_DataSource *__cdecl CppTest_Ds(const char * dataSourceName); 


extern CppTest_DataSource *__cdecl CppTest_DsCsv(const char * fileName, char separator, int useCollumns, int trimValues); 
#line 501 "C:\\Program Files (x86)\\Parasoft\\C++test for Visual Studio\\9.2\\engine\\runtime\\include\\cpptest.h"
static const char *CPPTEST_DS_GET_CSTR(const char *name) 
{ 
return (((cpptestGetCurrentDataSource() || cpptestDsNotInitialized()), ((cpptestGetCurrentDataSource()->getCStr) || cpptestDsMethodNotInitialized("getCStr"))), (cpptestGetCurrentDataSource()->getCStr))(cpptestGetCurrentDataSource(), name); 
} 

static const CppTest_wchar_t *CPPTEST_DS_GET_WCSTR(const char *name) 
{ 
return (((cpptestGetCurrentDataSource() || cpptestDsNotInitialized()), ((cpptestGetCurrentDataSource()->getWCStr) || cpptestDsMethodNotInitialized("getWCStr"))), (cpptestGetCurrentDataSource()->getWCStr))(cpptestGetCurrentDataSource(), name); 
} 

static const char *CPPTEST_DS_GET_MEM_BUFFER(const char *name, unsigned *sizePtr) 
{ 
return (((cpptestGetCurrentDataSource() || cpptestDsNotInitialized()), ((cpptestGetCurrentDataSource()->getMemBuffer) || cpptestDsMethodNotInitialized("getMemBuffer"))), (cpptestGetCurrentDataSource()->getMemBuffer))(cpptestGetCurrentDataSource(), name, sizePtr); 
} 
static __int64 CPPTEST_DS_GET_INTEGER(const char *name) 
{ 
return (((cpptestGetCurrentDataSource() || cpptestDsNotInitialized()), ((cpptestGetCurrentDataSource()->getInteger) || cpptestDsMethodNotInitialized("getInteger"))), (cpptestGetCurrentDataSource()->getInteger))(cpptestGetCurrentDataSource(), name); 
} 
static unsigned __int64 CPPTEST_DS_GET_UINTEGER(const char *name) 
{ 
return (((cpptestGetCurrentDataSource() || cpptestDsNotInitialized()), ((cpptestGetCurrentDataSource()->getUInteger) || cpptestDsMethodNotInitialized("getUInteger"))), (cpptestGetCurrentDataSource()->getUInteger))(cpptestGetCurrentDataSource(), name); 
} 
static double CPPTEST_DS_GET_FLOAT(const char *name) 
{ 
return (((cpptestGetCurrentDataSource() || cpptestDsNotInitialized()), ((cpptestGetCurrentDataSource()->getFloat) || cpptestDsMethodNotInitialized("getFloat"))), (cpptestGetCurrentDataSource()->getFloat))(cpptestGetCurrentDataSource(), name); 
} 
static int CPPTEST_DS_GET_BOOL(const char *name) 
{ 
return (((cpptestGetCurrentDataSource() || cpptestDsNotInitialized()), ((cpptestGetCurrentDataSource()->getBool) || cpptestDsMethodNotInitialized("getBool"))), (cpptestGetCurrentDataSource()->getBool))(cpptestGetCurrentDataSource(), name); 
} 
static char CPPTEST_DS_GET_CHAR(const char *name) 
{ 
return (((cpptestGetCurrentDataSource() || cpptestDsNotInitialized()), ((cpptestGetCurrentDataSource()->getChar) || cpptestDsMethodNotInitialized("getChar"))), (cpptestGetCurrentDataSource()->getChar))(cpptestGetCurrentDataSource(), name); 
} 
static unsigned CPPTEST_DS_GET_ITERATION() 
{ 
return (((cpptestGetCurrentDataSource() || cpptestDsNotInitialized()), ((cpptestGetCurrentDataSource()->getIteration) || cpptestDsMethodNotInitialized("getIteration"))), (cpptestGetCurrentDataSource()->getIteration))(cpptestGetCurrentDataSource()); 
} 
static int CPPTEST_DS_HAS_COLUMN(const char *name) 
{ 
if (cpptestGetCurrentDataSource() && ((((cpptestGetCurrentDataSource() || cpptestDsNotInitialized()), ((cpptestGetCurrentDataSource()->hasColumn) || cpptestDsMethodNotInitialized("hasColumn"))), (cpptestGetCurrentDataSource()->hasColumn)))) { 
return (((cpptestGetCurrentDataSource() || cpptestDsNotInitialized()), ((cpptestGetCurrentDataSource()->hasColumn) || cpptestDsMethodNotInitialized("hasColumn"))), (cpptestGetCurrentDataSource()->hasColumn))(cpptestGetCurrentDataSource(), name); 
}  
return 0; 
} 
#line 780
typedef int CPPTEST_CALL_ROUTINE(const char *); 
#line 20 "D:\\CRRC\\ATP-UT1-2607-copy\\ATP\\ATP\\test\\UT1\\stubs\\autogenerated\\auto_344e85af.c"
int SetSendAtoairConditionerStaticTestReq(); 
#if defined(CPPTEST_AUTO_STUB_SetSendAtoairConditionerStaticTestReq)
#line 21
int CppTest_Auto_Stub_SetSendAtoairConditionerStaticTestReq_SetSendAtoairConditionerStaticTestReq(void) 
{ 
return 0; 
} 
#endif

int packSendTacAlarmInfo(); 
#if defined(CPPTEST_AUTO_STUB_packSendTacAlarmInfo)
#line 28
int CppTest_Auto_Stub_packSendTacAlarmInfo_packSendTacAlarmInfo(void) 
{ 
return 0; 
} 
#endif

int SetSendAtotrainAirTightnessTestReq(); 
#if defined(CPPTEST_AUTO_STUB_SetSendAtotrainAirTightnessTestReq)
#line 35
int CppTest_Auto_Stub_SetSendAtotrainAirTightnessTestReq_SetSendAtotrainAirTightnessTestReq(void) 
{ 
return 0; 
} 
#endif

int GetRcvAtoFamMode(); 
#if defined(CPPTEST_AUTO_STUB_GetRcvAtoFamMode)
#line 42
int CppTest_Auto_Stub_GetRcvAtoFamMode_GetRcvAtoFamMode(void) 
{ 
return 0; 
} 
#endif

int SetSendAtoemergencyVentilationTestReq(); 
#if defined(CPPTEST_AUTO_STUB_SetSendAtoemergencyVentilationTestReq)
#line 49
int CppTest_Auto_Stub_SetSendAtoemergencyVentilationTestReq_SetSendAtoemergencyVentilationTestReq(void) 
{ 
return 0; 
} 
#endif

int SetSendAtototalWindThroughTestReq(); 
#if defined(CPPTEST_AUTO_STUB_SetSendAtototalWindThroughTestReq)
#line 56
int CppTest_Auto_Stub_SetSendAtototalWindThroughTestReq_SetSendAtototalWindThroughTestReq(void) 
{ 
return 0; 
} 
#endif

int SetSendAtomechanicalBrakingTestReq(); 
#if defined(CPPTEST_AUTO_STUB_SetSendAtomechanicalBrakingTestReq)
#line 63
int CppTest_Auto_Stub_SetSendAtomechanicalBrakingTestReq_SetSendAtomechanicalBrakingTestReq(void) 
{ 
return 0; 
} 
#endif

#line 1 "__TEST_HARNESS__"
;

