#include "cpptest.h"

#include "D:\CRRC\ATP-UT1-2607-copy\ATP\ATP\src\AppLogic\PeriodHandle\RomteEBManage\RemoteEBHandle.c"
#include "D:\CRRC\ATP-UT1-2607-copy\ATP\ATP\test\UT1\tests\autogenerated\source\applogic\periodhandle\romteebmanage\TestSuite_RemoteEBHandle.c"

