#include "cpptest.h"

#include "D:\CRRC\ATP-UT1-2607-copy\ATP\ATP\src\AppLogic\PeriodHandle\TimeManage\TimeHandle.c"
#include "D:\CRRC\ATP-UT1-2607-copy\ATP\ATP\test\UT1\tests\autogenerated\source\applogic\periodhandle\timemanage\TestSuite_TimeHandle.c"

