#include "cpptest.h"

#include "D:\CRRC\ATP-UT1-2607-copy\ATP\ATP\src\AppLogic\PeriodHandle\ProtectionManage\ProtectionHandle.c"
#include "D:\CRRC\ATP-UT1-2607-copy\ATP\ATP\test\UT1\tests\autogenerated\source\applogic\periodhandle\protectionmanage\TestSuite_ProtectionHandle_c.c"

