#include "cpptest.h"

#include "D:\CRRC\ATP-UT1-2607-copy\ATP\ATP\src\AppLogic\PeriodHandle\TractionBrakeManage\TractionBrakeHandle.c"
#include "D:\CRRC\ATP-UT1-2607-copy\ATP\ATP\test\UT1\tests\autogenerated\source\applogic\periodhandle\tractionbrakemanage\TestSuite_TractionBrakeHandle_c.c"

